basePath: /
definitions:
  gin.H:
    additionalProperties: {}
    type: object
  go-test_internal_store.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  internal_handler.UserInput:
    properties:
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 这是一个基于 Gin + GORM 的用户管理后台 API 文档
  title: Go-Test User API
  version: "1.0"
paths:
  /user:
    get:
      consumes:
      - application/json
      description: 获取所有用户的详细信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/go-test_internal_store.User'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: 获取所有用户
      tags:
      - User
    post:
      consumes:
      - application/json
      description: 创建新用户
      parameters:
      - description: 用户信息
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_handler.UserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/go-test_internal_store.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: 创建用户
      tags:
      - User
  /user/{id}:
    delete:
      consumes:
      - application/json
      description: 根据 ID 删除用户
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: 删除用户
      tags:
      - User
    get:
      consumes:
      - application/json
      description: 根据 ID 获取用户的详细信息
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-test_internal_store.User'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
      summary: 获取单个用户
      tags:
      - User
    put:
      consumes:
      - application/json
      description: 根据 ID 更新用户的详细信息
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User Input
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_handler.UserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/go-test_internal_store.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: 更新用户信息
      tags:
      - User
swagger: "2.0"
